apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rio-servicemonitor
  namespace: rio
  labels:
    team: frontend
spec:
  namespaceSelector:
    matchNames:
    - rio
  selector:
    matchLabels:
      app.kubernetes.io/instance: rio
  endpoints:
  #- path: /metrics
  #- port: http
  - params:
      module: [http_2xx]
  - relabelings:
    - sourceLabels: [__meta_kubernetes_service_annotation_prometheus_io_probe]
      action: keep
      regex: "true"
    - sourceLabels: [__address__]
      targetLabel: __param_target
    - targetLabel: __address__
      replacement: blackbox
    - sourceLabels: [__param_target]
      targetLabel: instance
    - action: labelmap
      regex: __meta_kubernetes_service_label_(.+)
    - sourceLabels: [__meta_kubernetes_namespace]
      targetLabel: kubernetes_namespace
    - sourceLabels: [__meta_kubernetes_service_name]
      targetLabel: kubernetes_name
